print("Enter the principle amount, rate of interest ,time:")
principle_amount=int(input(""))
rate=int(input(""))
time=int(input(""))
print("The simple interest is",(principle_amount*rate*time)/100)